openapi: 3.0.0

info:
  title: Composer API
  version: 1.0.0
  description: API for managing composers

paths:
  /composers:
    get:
      tags:
        - Composers
      summary: returns a list of composers documents
      description: API for returning a list of composers from MongoDB Atlas
      responses:
        '200':
          description: Composer documnets
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception
    post:
      tags:
        - Composers
      summary: Creates a new composer object
      description: API for adding new composer object
      requestBody:
        content:
          application/json:
          description: Composer's information
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
      responses:
        '200':
          description: User added
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception

  /composers/{id}:
    get:
      tags:
        - Composers
      summary: returns a composer document
      description: API for returning a single composer object from MongoDB
      parameters:
        - in: path
          name: id
          required: true
          description: The composerId requestred by the user.
          schema:
            type: string
          x-placeholder: id - The composerId requested by the user.
      responses:
        '200':
          description: Composer document in JSON format
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception
