openapi: 3.0.0

info:
  title: Composer API
  version: 1.0.0
  description: API for managing composers

paths:
  /composers:
    get:
      tags:
        - Composers
      summary: Find all composers
      responses:
        '200':
          description: OK
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception
    post:
      tags:
        - Composers
      summary: Create a composer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
      responses:
        '200':
          description: OK
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception

  /composers/{id}:
    get:
      tags:
        - Composers
      summary: Find a composer by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception
